-- Run with psql --no-psqlrc --quiet --tuples-only --no-align --file export-postgres.sql --output /secure/path/pirot.ndjson
-- One consistent READ ONLY snapshot. UTC matches hibernate.jdbc.time_zone in the legacy application.
BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;
SET LOCAL TIME ZONE 'UTC';
SELECT jsonb_build_object('_type','entity','kind','uruns','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'urunAdi',t.urun_adi,'stok',t.stok::text,'stokSiniri',t.stok_siniri::text,'musteriFiyati',t.musteri_fiyati::text,'birim',t.birim,'dayanismaUrunu',t.dayanisma_urunu,'satista',t.satista,'urunKategorisi',t.urun_kategorisi,'active',t.active,'uretici',CASE WHEN t.uretici_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.uretici_id::text) END,'urunSorumlusu',CASE WHEN t.urun_sorumlusu_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.urun_sorumlusu_id::text) END,'kdvKategorisi',CASE WHEN t.kdv_kategorisi_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.kdv_kategorisi_id::text) END,'urunFiyatHesap',CASE WHEN (SELECT r.id FROM urun_fiyat_hesap r WHERE r.urun_id=t.id) IS NULL THEN NULL ELSE jsonb_build_object('id',(SELECT r.id FROM urun_fiyat_hesap r WHERE r.urun_id=t.id)::text) END)) FROM urun t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','ureticis','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'adi',t.adi,'adres',t.adres,'bankaBilgileri',t.banka_bilgileri,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END)) FROM uretici t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','kdv-kategorisis','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'kategoriAdi',t.kategori_adi,'kdvOrani',t.kdv_orani::text)) FROM kdv_kategorisi t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','urun-fiyats','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'fiyat',t.fiyat::text,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END,'urun',CASE WHEN t.urun_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.urun_id::text) END)) FROM urun_fiyat t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','urun-fiyat-hesaps','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'faturaTipi',t.fatura_tipi,'amortisman',t.amortisman::text,'giderPusulaMustahsil',t.gider_pusula_mustahsil::text,'dukkanGider',t.dukkan_gider::text,'kooperatifCalisma',t.kooperatif_calisma::text,'dayanisma',t.dayanisma::text,'fire',t.fire::text,'urun',CASE WHEN t.urun_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.urun_id::text) END)) FROM urun_fiyat_hesap t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','kisilers','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'kisiAdi',t.kisi_adi,'notlar',t.notlar,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'active',t.active)) FROM kisiler t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','satis','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'toplamTutar',t.toplam_tutar::text,'ortagaSatis',t.ortaga_satis,'kartliSatis',t.kartli_satis,'sonraOdeme',t.sonra_odeme,'odendi',t.odendi,'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END,'kisi',CASE WHEN t.kisi_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.kisi_id::text) END,'borcAlacak',CASE WHEN (SELECT r.id FROM borc_alacak r WHERE r.satis_id=t.id) IS NULL THEN NULL ELSE jsonb_build_object('id',(SELECT r.id FROM borc_alacak r WHERE r.satis_id=t.id)::text) END,'iptal',t.iptal,'nobetAcilisId',t.nobet_acilis_id::text,'duzeltildi',t.duzeltildi)) FROM satis t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','satis-stok-hareketleris','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'miktar',t.miktar::text,'tutar',t.tutar::text,'urun',CASE WHEN t.urun_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.urun_id::text) END,'satis',CASE WHEN t.satis_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.satis_id::text) END)) FROM satis_stok_hareketleri t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','stok-girisis','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'miktar',t.miktar::text,'agirlik',t.agirlik::text,'notlar',t.notlar,'stokHareketiTipi',t.stok_hareketi_tipi,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END,'urun',CASE WHEN t.urun_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.urun_id::text) END)) FROM stok_girisi t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','giders','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'tutar',t.tutar::text,'notlar',t.notlar,'giderTipi',t.gider_tipi,'odemeAraci',t.odeme_araci,'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END,'iptal',t.iptal,'nobetAcilisId',t.nobet_acilis_id::text,'duzeltildi',t.duzeltildi)) FROM gider t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','virmen','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'tutar',t.tutar::text,'notlar',t.notlar,'cikisHesabi',t.cikis_hesabi,'girisHesabi',t.giris_hesabi,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END,'iptal',t.iptal,'nobetAcilisId',t.nobet_acilis_id::text,'duzeltildi',t.duzeltildi)) FROM virman t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','borc-alacaks','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'tutar',t.tutar::text,'notlar',t.notlar,'odemeAraci',t.odeme_araci,'hareketTipi',t.hareket_tipi,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END,'urun',CASE WHEN t.urun_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.urun_id::text) END,'satis',CASE WHEN t.satis_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.satis_id::text) END)) FROM borc_alacak t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','kasa-hareketleris','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'kasaMiktar',t.kasa_miktar::text,'hareket',t.hareket,'degisimTutari',t.degisim_tutari::text,'hareketTipi',t.hareket_tipi,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'duzeltmeId',t.duzeltme_id::text)) FROM kasa_hareketleri t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','nobet-hareketleris','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'kasa',t.kasa::text,'pirot',t.pirot::text,'fark',t.fark::text,'farkDenge',t.fark_denge::text,'nobetSuresi',t.nobet_suresi::text,'notlar',t.notlar,'acilisKapanis',t.acilis_kapanis,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'user',CASE WHEN t.user_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.user_id::text) END,'acilisId',t.acilis_id::text,'kapanisDokumu',t.kapanis_dokumu)) FROM nobet_hareketleri t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','uretici-odemeleris','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'tutar',t.tutar::text,'sonGuncellenmeTarihi',to_char(t.son_guncellenme_tarihi,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'uretici',CASE WHEN t.uretici_id IS NULL THEN NULL ELSE jsonb_build_object('id',t.uretici_id::text) END)) FROM uretici_odemeleri t ORDER BY t.id;
SELECT jsonb_build_object('_type','entity','kind','nobet-duzeltmeler','data',jsonb_build_object('id',t.id::text,'tenantId',t.tenant_id::text,'odemeKullanici',t.odeme_kullanici,'kaynakTipi',t.kaynak_tipi,'kaynakId',t.kaynak_id::text,'kapanisId',t.kapanis_id::text,'nobetAcilisId',t.nobet_acilis_id::text,'neden',t.neden,'islem',t.islem,'kullanici',t.kullanici,'tarih',to_char(t.tarih,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'onceki',t.onceki,'sonraki',t.sonraki,'kasaDegisimi',t.kasa_degisimi::text,'bekleyenKasa',t.bekleyen_kasa::text,'nakitSimdi',t.nakit_simdi,'odemeTarihi',to_char(t.odeme_tarihi,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'odemeNobetId',t.odeme_nobet_id::text)) FROM nobet_duzeltme t ORDER BY t.id;
SELECT jsonb_build_object('_type','tenant','data',jsonb_build_object('id',t.id::text,'tenantName',t.tenant_name)) FROM koop_tenant t ORDER BY t.id;
SELECT jsonb_build_object('_type','user','data',to_jsonb(u)-'id'-'tenant_id'-'reset_date'-'created_date'-'last_modified_date'||jsonb_build_object('id',u.id::text,'tenant_id',u.tenant_id::text,'reset_date',to_char(u.reset_date,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'created_date',to_char(u.created_date,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'last_modified_date',to_char(u.last_modified_date,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'authorities',(SELECT coalesce(jsonb_agg(a.authority_name ORDER BY a.authority_name),'[]'::jsonb) FROM koop_user_authority a WHERE a.user_id=u.id))) FROM koop_user u ORDER BY u.id;
SELECT jsonb_build_object('_type','javers','data',jsonb_build_object('id',s.snapshot_pk::text,'entityId',g.local_id,'className',g.type_name,'state',s.state,'operation',s.type,'author',c.author,'at',c.commit_date_instant,'commitDate',c.commit_date::text,'properties',(SELECT coalesce(jsonb_object_agg(p.property_name,p.property_value),'{}'::jsonb) FROM jv_commit_property p WHERE p.commit_fk=c.commit_pk))) FROM jv_snapshot s JOIN jv_global_id g ON g.global_id_pk=s.global_id_fk JOIN jv_commit c ON c.commit_pk=s.commit_fk ORDER BY s.snapshot_pk;
SELECT jsonb_build_object('_type','audit','data',jsonb_build_object('id',a.event_id::text,'principal',a.principal,'event_type',a.event_type,'event_date',to_char(a.event_date,'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),'data',(SELECT coalesce(jsonb_object_agg(d.name,d.value),'{}'::jsonb) FROM koop_persistent_audit_evt_data d WHERE d.event_id=a.event_id))) FROM koop_persistent_audit_event a ORDER BY a.event_id;
COMMIT;
